<a href="https://colab.research.google.com/github/Sneider-Serrano/T-picos-en-Estadistica/blob/main/Bono_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy y Pandas en Ciencia de Datos: Uso, Ventajas y Desventajas para la Implementación de Algoritmos


## NumPy (*Numerical Python*)

### ¿Para qué se usa en ciencia de datos?

NumPy es la biblioteca fundamental para el cómputo numérico en Python. En ciencia de datos se utiliza principalmente para:

- Representar y manipular datos numéricos en forma de **arreglos multidimensionales (ndarrays)**.
- Realizar **operaciones matemáticas y estadísticas** de forma vectorizada (sin bucles explícitos).
- Servir como **base para otras bibliotecas** como Pandas, Scikit-learn, TensorFlow y SciPy, que internamente operan sobre arreglos NumPy.
- Ejecutar operaciones de **álgebra lineal** (multiplicación de matrices, descomposiciones) esenciales en algoritmos de Machine Learning.
- Generar **datos aleatorios** para simulaciones y pruebas de algoritmos.

###Ventajas

| Ventaja | Descripción |
|---|---|
| **Alto rendimiento** | Las operaciones vectorizadas se ejecutan en C/Fortran internamente, siendo hasta 100x más rápidas que los bucles de Python puro. |
| **Bajo consumo de memoria** | Un `ndarray` ocupa menos memoria que una lista de Python equivalente porque almacena datos de tipo homogéneo. |
| **Broadcasting** | Permite operar arreglos de distintas formas sin necesidad de replicar datos, ahorrando memoria y código. |
| **Amplio ecosistema** | Es el estándar de facto; prácticamente todas las bibliotecas de ML y ciencia de datos lo utilizan. |
| **Operaciones matriciales nativas** | Ideal para implementar desde cero regresión lineal, redes neuronales, PCA, etc. |

###Desventajas

| Desventaja | Descripción |
|---|---|
| **Solo datos homogéneos** | Todos los elementos de un arreglo deben ser del mismo tipo (e.g., todos `float64`). No es adecuado para mezclar texto y números. |
| **Sin etiquetas** | Los arreglos no tienen nombres de columnas ni índices descriptivos, lo que dificulta la interpretación de datos tabulares. |
| **Manejo de datos faltantes limitado** | No tiene soporte nativo para valores `NaN` en arreglos enteros; requiere conversiones o uso de `np.nan` solo con flotantes. |
| **Curva de aprendizaje en indexación avanzada** | El *fancy indexing* y el *broadcasting* pueden resultar confusos para usuarios nuevos. |

---

## Pandas

### ¿Para qué se usa en ciencia de datos?

Pandas está diseñado para la **manipulación y análisis de datos tabulares y de series temporales**. En ciencia de datos se usa para:

- **Cargar, limpiar y transformar** conjuntos de datos desde archivos CSV, Excel, SQL, JSON, entre otros.
- Realizar **exploración de datos (EDA)**: estadísticas descriptivas, conteos, distribuciones.
- **Filtrar, agrupar y agregar** datos con una sintaxis expresiva similar a SQL.
- Gestionar **datos faltantes**: detección, eliminación e imputación.
- **Preparar los datos** antes de alimentar algoritmos de Machine Learning (codificación, normalización, división train/test).
- Trabajar con **series temporales**: remuestreo, ventanas deslizantes, interpolación.

###Ventajas

| Ventaja | Descripción |
|---|---|
| **Datos heterogéneos** | Un `DataFrame` puede contener columnas de distintos tipos (int, float, str, datetime) en la misma estructura. |
| **Etiquetas descriptivas** | Índices y nombres de columnas facilitan el acceso, la interpretación y la depuración de datos. |
| **Manejo robusto de datos faltantes** | Métodos como `.fillna()`, `.dropna()` e `.interpolate()` hacen sencillo tratar valores ausentes. |
| **Integración con el ecosistema** | Compatible con Matplotlib, Seaborn, Scikit-learn, SQLAlchemy y muchas otras bibliotecas. |
| **Operaciones tipo SQL** | `groupby`, `merge`, `pivot_table` y `join` permiten análisis complejos con pocas líneas de código. |

###Desventajas

| Desventaja | Descripción |
|---|---|
| **Mayor consumo de memoria** | Los `DataFrames` tienen una sobrecarga considerable respecto a los arreglos NumPy puros, especialmente con columnas de tipo `object`. |
| **Rendimiento inferior en operaciones numéricas puras** | Para álgebra lineal o cómputo intensivo, NumPy (o CuPy en GPU) es significativamente más rápido. |
| **No escala a Big Data de forma nativa** | Para conjuntos de datos que no caben en RAM se requieren alternativas como Dask, Polars o PySpark. |
| **API extensa y a veces inconsistente** | La gran cantidad de métodos y las diferencias entre versiones pueden generar confusión (e.g., `.ix` deprecado, diferencias entre `.loc` e `.iloc`). |
| **Iteración fila a fila es lenta** | Usar bucles `for` sobre filas de un DataFrame es muy ineficiente; se debe preferir vectorización o `.apply()`. |

---

> **Conclusión:** En la práctica, ambas bibliotecas son **complementarias**. Pandas se usa en las etapas de carga, exploración y preparación de datos, mientras que NumPy opera en el núcleo matemático de los algoritmos. La mayoría de los flujos de trabajo en ciencia de datos utilizan las dos de forma conjunta.

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])
b = np.array([[1, 2], [3, 4], [1, 2]])
print(a)
print(b)

[1 2 3 4]
[[1 2]
 [3 4]
 [1 2]]


In [3]:
b*2

array([[2, 4],
       [6, 8],
       [2, 4]])

In [4]:
lista = [1, 2, 3]
arr = np.array([1, 2, 3])

In [5]:
lista*2

[1, 2, 3, 1, 2, 3]

In [6]:
arr*2 #Hay una interpretación de los arreglos de tipo Numpy más apegados a lo que vemos en los
# objetos matemáticos como los vectores

array([2, 4, 6])

In [8]:
arr.shape

(3,)

In [9]:
b.shape #Arreglo de tres componentes cada uno con dos elementos

(3, 2)

In [10]:
arr.ndim

1

In [11]:
b.ndim #Número de elementos por cada componente

2

In [12]:
b.dtype

dtype('int64')

In [13]:
b.size # Cantidad de elementos de todas las componentes

6

# **Arreglos especiales**

In [14]:
np.zeros((2, 3)) #Todo lleno de cero: 2 componentes y 3 elementos por componente

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((2, 3)) #Todo lleno de uno: 2 componentes y 3 elementos por componente

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.eye(3) #La matriz identidad de una matriz cuadrada de tamaño 3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.arange(0, 10, 2) # Del 0 hasta el 10 (sin tomar el 10), separado por 2

array([0, 2, 4, 6, 8])

In [18]:
np.linspace(0, 1, 5) # 5 elementos quistantes entre el 0 y el 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
arry = np.array([10, 20, 30, 40])
arry

array([10, 20, 30, 40])

In [20]:
arry[-1]

np.int64(40)

In [21]:
arry[0:2] #Tomando del índice 0 al 2 (sin tomar el 2)

array([10, 20])

In [22]:
matri = np.array([[1,2,3], [4,5,6]])

In [23]:
matri[0,1] # El índice 1 de la 0-ésima fila

np.int64(2)

In [24]:
matri[:,0] # Es la 0-ésima columna

array([1, 4])

In [25]:
matri[1:]

array([[4, 5, 6]])

In [26]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a + b

array([5, 7, 9])

In [27]:
a * b #Prodcuto de Hadamard entre dos arreglos

array([ 4, 10, 18])

In [28]:
matri1 = np.array([[2,3,3], [4,5,6]])
matri1 * matri #Producto de Hadamard

array([[ 2,  6,  9],
       [16, 25, 36]])

In [29]:
[x * 2 for x in lista]

[2, 4, 6]

**Ejemplo de Numpy**

In [30]:
c = np.array([1.65, 1.58, 1.82, 1.70, 1.50, 1.82, 1.74])
print(np.mean(c), np.median(c), np.std(c), np.sum(c), np.min(c), np.max(c))

1.6871428571428573 1.7 0.11093296376181246 11.81 1.5 1.82


**Manipulación de arreglos**

In [31]:
d = np.array([1,2,3,4,5,6]) #Inicialmente tiene 6 elementos de un elemento cada una
d.reshape(2,3) # Cambia a 2 componentes cada una con 3 elementos

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
np.concatenate([d,a]) # Concatenar arreglos

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [33]:
np.concatenate(d.reshape(2,3))

array([1, 2, 3, 4, 5, 6])

In [34]:
d.reshape(2,3).flatten() # Vectoriza la matriz

array([1, 2, 3, 4, 5, 6])

In [36]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]]) # Multiplicación de matrices

np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [37]:
np.linalg.inv(a) # Inversa de una matriz

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [38]:
np.linalg.matrix_transpose(a)

array([[1, 3],
       [2, 4]])

In [39]:
np.random.rand(10) #Genera 10 valores de una distribución uniforme en el intervalo (0,1)

array([0.55409773, 0.4031045 , 0.23676508, 0.26359509, 0.35538893,
       0.38397146, 0.32497483, 0.89884012, 0.18661405, 0.23431341])

In [40]:
np.random.randint(0,10) #Genera un valor entero entre 0 y el entero anterior al 10

8

In [41]:
np.random.randn(8) # Genera 8 valores aletorios de una distribución normal con
# media 0 y desviación estándar 1

array([ 0.6935198 , -1.29032315,  0.40981018, -0.45118188, -0.34610692,
       -0.36034926,  0.84910548, -1.47369971])

In [42]:
e = np.array([1,2,3,4,5]) # Filtrado y condiciones
f = e[e > 3]
f

array([4, 5])

In [43]:
e[(e >2) & (e < 5)] #Note que el y es &. El o es |

array([3, 4])

In [44]:
np.where(e > 3, 1, 0) # Donde e>3 anotamos un 1. Donde no, un 0

array([0, 0, 0, 1, 1])

In [45]:
np.where(e > 3, 1, e) #Los valores que no queremos reemplazar, anotamos el mismo objeto

array([1, 2, 3, 1, 1])

**Ahora con Pandas**

In [46]:
import pandas as pd

In [47]:
s = pd.Series([10, 20, 30]) # Vector columna
s

,0
0,10
1,20
2,30


In [48]:
df = pd.DataFrame({
    'nombre': ['Ana', 'Luis', 'Carlos', 'Marta'],
    'ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá'],
    'edad': [23, 30, 35, 28],
    'salario': [1500, 2000, 3000, 2500]
}) # Creando data.frames
df

,nombre,ciudad,edad,salario
0,Ana,Bogotá,23,1500
1,Luis,Medellín,30,2000
2,Carlos,Cali,35,3000
3,Marta,Bogotá,28,2500


In [49]:
salario_promedio = df['salario'].mean()
print(f"El salario promedio es: {salario_promedio}")

El salario promedio es: 2250.0


In [50]:
df.head(2)

,nombre,ciudad,edad,salario
0,Ana,Bogotá,23,1500
1,Luis,Medellín,30,2000


In [51]:
df.info() # Tipos de datos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   nombre   4 non-null      object
 1   ciudad   4 non-null      object
 2   edad     4 non-null      int64 
 3   salario  4 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes


In [52]:
df.describe() # Estadísticas descriptivas para variables cuantitativas

,edad,salario
count,4.000000,4.000000
mean,29.000000,2250.000000
std,4.966555,645.497224
min,23.000000,1500.000000
25%,26.750000,1875.000000
50%,29.000000,2250.000000
75%,31.250000,2625.000000
max,35.000000,3000.000000


In [53]:
df.shape #(filas, columnas)

(4, 4)

In [54]:
df['edad'] # Para imprimir la columna edad

,edad
0,23
1,30
2,35
3,28


In [55]:
df[['nombre', 'edad']] # Selección de columnas utilizando una lista con los respectivos nombres

,nombre,edad
0,Ana,23
1,Luis,30
2,Carlos,35
3,Marta,28


In [56]:
df[df['edad'] > 25] # Selección de filas

,nombre,ciudad,edad,salario
1,Luis,Medellín,30,2000
2,Carlos,Cali,35,3000
3,Marta,Bogotá,28,2500


In [57]:
df[(df['edad'] > 20) & (df['edad'] < 30)] #Selección de filas de edad entre 20 y 30 años

,nombre,ciudad,edad,salario
0,Ana,Bogotá,23,1500
3,Marta,Bogotá,28,2500


In [58]:
data = {
    'nombre': ['Ana', 'Luis', 'Carlos', 'Marta', None],
    'ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá', 'Cali'],
    'edad': [23, np.nan, 30, 35, 28],
    'salario': [1000, 2000, 3000, 2500, 1500]
}
data

{'nombre': ['Ana', 'Luis', 'Carlos', 'Marta', None],
 'ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá', 'Cali'],
 'edad': [23, nan, 30, 35, 28],
 'salario': [1000, 2000, 3000, 2500, 1500]}

In [59]:
data1 = pd.DataFrame(data)
data1

,nombre,ciudad,edad,salario
0,Ana,Bogotá,23.0,1000
1,Luis,Medellín,NaN,2000
2,Carlos,Cali,30.0,3000
3,Marta,Bogotá,35.0,2500
4,None,Cali,28.0,1500


In [60]:
data1.isnull() #Valores faltantes

,nombre,ciudad,edad,salario
0,False,False,False,False
1,False,False,True,False
2,False,False,False,False
3,False,False,False,False
4,True,False,False,False


In [61]:
data1.isnull().sum() # Suma los valores por columnas: 1 si es faltante, 0 si no.

,0
nombre,1
ciudad,0
edad,1
salario,0


In [62]:
data2 = data1.dropna() #Elimina las filas con valores faltantes
data2

,nombre,ciudad,edad,salario
0,Ana,Bogotá,23.0,1000
2,Carlos,Cali,30.0,3000
3,Marta,Bogotá,35.0,2500


In [63]:
data1.dropna(subset=['salario']) # Se eliminan las filas con valores faltantes,
# únicamente en la columna salario

,nombre,ciudad,edad,salario
0,Ana,Bogotá,23.0,1000
1,Luis,Medellín,NaN,2000
2,Carlos,Cali,30.0,3000
3,Marta,Bogotá,35.0,2500
4,None,Cali,28.0,1500


In [64]:
data1['edad'] = data1['edad'].fillna(data1['edad'].mean()) #Rellena los valores faltantes con la media
data1["nombre"] = data1['nombre'].fillna('Desconocido')
data1

,nombre,ciudad,edad,salario
0,Ana,Bogotá,23.0,1000
1,Luis,Medellín,29.0,2000
2,Carlos,Cali,30.0,3000
3,Marta,Bogotá,35.0,2500
4,Desconocido,Cali,28.0,1500


In [65]:
data1['ciudad'] = data1['ciudad'].replace('Bogotá', 'BOGOTA')
data1

,nombre,ciudad,edad,salario
0,Ana,BOGOTA,23.0,1000
1,Luis,Medellín,29.0,2000
2,Carlos,Cali,30.0,3000
3,Marta,BOGOTA,35.0,2500
4,Desconocido,Cali,28.0,1500


In [66]:
data4 = data1['ciudad'].drop_duplicates() #Elimina los valores duplicados
data4

,ciudad
0,BOGOTA
1,Medellín
2,Cali


In [67]:
data5 = {
    'nombre': ['Ana', 'Luis', 'Carlos', 'Marta', 'Juan'],
    'ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá', 'Cali'],
    'edad': [23, 30, 35, 28, 23],
}
data5 = pd.DataFrame(data5)
data5

,nombre,ciudad,edad
0,Ana,Bogotá,23
1,Luis,Medellín,30
2,Carlos,Cali,35
3,Marta,Bogotá,28
4,Juan,Cali,23


In [68]:
data6 = data5.drop_duplicates()
data6

,nombre,ciudad,edad
0,Ana,Bogotá,23
1,Luis,Medellín,30
2,Carlos,Cali,35
3,Marta,Bogotá,28
4,Juan,Cali,23


In [69]:
import pandas as pd

dfn = pd.DataFrame({
    'id': [1, 2, 3, 4, ],
    'nombre': ['Ana', 'Luis', 'Carlos', 'Marta'],
    'ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá'],
    'edad': [23, 30, 35, 28],
    'salario': [1000, 2000, 3000, 1500]
})
dfn

,id,nombre,ciudad,edad,salario
0,1,Ana,Bogotá,23,1000
1,2,Luis,Medellín,30,2000
2,3,Carlos,Cali,35,3000
3,4,Marta,Bogotá,28,1500


In [70]:
dfn['salario_anual'] = dfn['salario'] * 12 # Aplicar función
dfn['edad_doble'] = dfn['edad'].apply(lambda x: x * 2)
dfn

,id,nombre,ciudad,edad,salario,salario_anual,edad_doble
0,1,Ana,Bogotá,23,1000,12000,46
1,2,Luis,Medellín,30,2000,24000,60
2,3,Carlos,Cali,35,3000,36000,70
3,4,Marta,Bogotá,28,1500,18000,56


In [71]:
dfn = dfn.rename(columns={'edad': 'age'})
dfn

,id,nombre,ciudad,age,salario,salario_anual,edad_doble
0,1,Ana,Bogotá,23,1000,12000,46
1,2,Luis,Medellín,30,2000,24000,60
2,3,Carlos,Cali,35,3000,36000,70
3,4,Marta,Bogotá,28,1500,18000,56


In [72]:
grupo = dfn.groupby('ciudad')['salario'].mean()
grupo

,salario
ciudad,
Bogotá,1250.0
Cali,3000.0
Medellín,2000.0


In [73]:
ordenado = dfn.sort_values(by = 'age')
ordenado

,id,nombre,ciudad,age,salario,salario_anual,edad_doble
0,1,Ana,Bogotá,23,1000,12000,46
3,4,Marta,Bogotá,28,1500,18000,56
1,2,Luis,Medellín,30,2000,24000,60
2,3,Carlos,Cali,35,3000,36000,70


In [74]:
dfn1 = pd.DataFrame({
    'id': [1, 2, 3, 4],
    'departamento': ['Ventas', 'IT', 'RRHH', 'MARKETING']})

merge = pd.merge(dfn, dfn1, on = 'id')
merge

,id,nombre,ciudad,age,salario,salario_anual,edad_doble,departamento
0,1,Ana,Bogotá,23,1000,12000,46,Ventas
1,2,Luis,Medellín,30,2000,24000,60,IT
2,3,Carlos,Cali,35,3000,36000,70,RRHH
3,4,Marta,Bogotá,28,1500,18000,56,MARKETING


In [75]:
valores = dfn.values
valores

array([[1, 'Ana', 'Bogotá', 23, 1000, 12000, 46],
       [2, 'Luis', 'Medellín', 30, 2000, 24000, 60],
       [3, 'Carlos', 'Cali', 35, 3000, 36000, 70],
       [4, 'Marta', 'Bogotá', 28, 1500, 18000, 56]], dtype=object)

In [76]:
arr = np.array([10, 20, 30])
df = pd.DataFrame(arr)
df

,0
0,10
1,20
2,30
